language: node_js
node_js:
  - '8'
  - '10'
before_script:
  - npm install -g npm@latest
script:
  - npm run coverage
  - npm run test:features
branches:
  except:
    - /^v[0-9]\.[0-9]\.[0-9]$/
after_success:
- npm run report-coverage
notifications:
  hipchat:
    rooms:
      - secure: ARSdRSe6kV1tSP/Sg2s3GEgkewY5kaIDIhE9KOWBeOizQiY4Qfxy+B94fir8EN+/Q8T5Xie89fchHiYPbMzwQrNUKMQUsvy+12cY8Q3U/xuICCzvc329ii7NLmtciJWlI7cgbTwfYVrqkipgvVXG/rFiCMwM0eERBQ2FZug6rWM=
    template:
      - '%{repository}#%{build_number} (%{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Compare</a>)'
    format: html
    on_success: change
    on_failure: change
sudo: false
