export const product = 'product'
export const productType = 'productType'
export const price = 'price'
export const stock = 'stock'
export const category = 'category'
export const customer = 'customer'
export const discount = 'discount'
